# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-07 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20181206_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='card.List'),
            preserve_default=False,
        ),
    ]
